/obj/structure/retail/clothing_store
	desc = "Purchase all the finest outfits... Or don't, wagie."
	products_list = list(new /datum/data/vending_product("crimson red dress", /obj/item/clothing/under/vampire/primogen_toreador/female	, 350),
		new /datum/data/vending_product("black dress", /obj/item/clothing/under/vampire/business, 250),
		new /datum/data/vending_product("evening gown, red", /obj/item/clothing/under/dress/redeveninggown, 300),
		new /datum/data/vending_product("pants, leather", /obj/item/clothing/under/vampire/leatherpants, 200),
		new /datum/data/vending_product("pants, khaki", /obj/item/clothing/under/pants/slacks, 10),
		new /datum/data/vending_product("pants, jeans", /obj/item/clothing/under/pants/jeans, 10),
		new /datum/data/vending_product("pants, camo", /obj/item/clothing/under/pants/camo, 10),
		new /datum/data/vending_product("shorts, khaki", /obj/item/clothing/under/shorts, 10),
		new /datum/data/vending_product("shorts, red", /obj/item/clothing/under/shorts/red, 10),
		new /datum/data/vending_product("shorts, black", /obj/item/clothing/under/shorts/black, 10),
		new /datum/data/vending_product("fancy gray suit", /obj/item/clothing/under/vampire/fancy_gray, 150),
		new /datum/data/vending_product("fancy red suit", /obj/item/clothing/under/vampire/fancy_red, 150),
		new /datum/data/vending_product("black luxury suit", /obj/item/clothing/under/vampire/ventrue, 50),
		new /datum/data/vending_product("black luxury suit skirt", /obj/item/clothing/under/vampire/ventrue/female, 50),
		new /datum/data/vending_product("white business suit", /obj/item/clothing/under/vampire/office, 50),
		new /datum/data/vending_product("black overcoat", /obj/item/clothing/under/vampire/rich, 45),
		new /datum/data/vending_product("burgundy suit", /obj/item/clothing/under/vampire/tremere, 35),
		new /datum/data/vending_product("burgundy suit skirt", /obj/item/clothing/under/vampire/tremere/female, 35),
		new /datum/data/vending_product("plain black suit", /obj/item/clothing/under/vampire/suit, 50),
		new /datum/data/vending_product("plain black suitskirt", /obj/item/clothing/under/vampire/suit/female, 50),
		new /datum/data/vending_product("plain red suit", /obj/item/clothing/under/vampire/sheriff, 80),
		new /datum/data/vending_product("plain red suitskirt", /obj/item/clothing/under/vampire/sheriff/female, 80),
		new /datum/data/vending_product("plain blue suit", /obj/item/clothing/under/vampire/clerk, 90),
		new /datum/data/vending_product("plain blue suitskirt", /obj/item/clothing/under/vampire/clerk/female, 90),
		new /datum/data/vending_product("cardigan skirt",  /obj/item/clothing/under/dress/skirt, 60),
		new /datum/data/vending_product("brown suit", /obj/item/clothing/under/vampire/archivist, 60),
		new /datum/data/vending_product("brown suitskirt", /obj/item/clothing/under/vampire/archivist/female, 60),
		new /datum/data/vending_product("popular outfit", /obj/item/clothing/under/vampire/scenepink, 20),
		new /datum/data/vending_product("moody attire", /obj/item/clothing/under/vampire/scenemoody, 20),
		new /datum/data/vending_product("pim attire", /obj/item/clothing/under/vampire/scenezim, 20),
		new /datum/data/vending_product("revealing outfit", /obj/item/clothing/under/vampire/sceneleopard, 20),
		new /datum/data/vending_product("flamboyant outfit", /obj/item/clothing/under/vampire/toreador, 30),
		new /datum/data/vending_product("female flamboyant outfit", /obj/item/clothing/under/vampire/toreador/female, 30),
		new /datum/data/vending_product("purple and black outfit", /obj/item/clothing/under/vampire/sexy, 25),
		new /datum/data/vending_product("slick jacket", /obj/item/clothing/under/vampire/slickback, 25),
		new /datum/data/vending_product("tracksuit", /obj/item/clothing/under/vampire/sport, 25),
		new /datum/data/vending_product("tracksuit, athletic", /obj/item/clothing/under/trackpants, 25),
		new /datum/data/vending_product("tracksuit, athletic blue", /obj/item/clothing/under/trackpants/blue, 25),
		new /datum/data/vending_product("tracksuit, athletic green", /obj/item/clothing/under/trackpants/green, 25),
		new /datum/data/vending_product("tracksuit, athletic white", /obj/item/clothing/under/trackpants/white, 25),
		new /datum/data/vending_product("tracksuit, athletic red", /obj/item/clothing/under/trackpants/red, 25),
		new /datum/data/vending_product("grimey pants", /obj/item/clothing/under/vampire/malkavian, 20),
		new /datum/data/vending_product("odd goth schoolgirl attire", /obj/item/clothing/under/vampire/malkavian/female, 20),
		new /datum/data/vending_product("gothic clothes", /obj/item/clothing/under/vampire/gothic, 20),
		new /datum/data/vending_product("punk attire", /obj/item/clothing/under/vampire/brujah, 20),
		new /datum/data/vending_product("female punk attire ", /obj/item/clothing/under/vampire/brujah/female, 20),
		new /datum/data/vending_product("pentagram shirt", /obj/item/clothing/under/vampire/baali, 20),
		new /datum/data/vending_product("pentagram skirt", /obj/item/clothing/under/vampire/baali/female, 20),
		new /datum/data/vending_product("emo outfit", /obj/item/clothing/under/vampire/emo, 20),
		new /datum/data/vending_product("red hipster outfit", /obj/item/clothing/under/vampire/red, 20),
		new /datum/data/vending_product("messy shirt", /obj/item/clothing/under/vampire/bouncer, 15),
		new /datum/data/vending_product("agent shirt", /obj/item/clothing/under/vampire/hound, 15),
		new /datum/data/vending_product("cheap shirt", /obj/item/clothing/under/vampire/homeless, 10),
		new /datum/data/vending_product("cheaper shirt", /obj/item/clothing/under/vampire/homeless/female, 5),
		new /datum/data/vending_product("blue overalls", /obj/item/clothing/under/vampire/mechanic, 20),
		new /datum/data/vending_product("black grunge outfit", /obj/item/clothing/under/vampire/black, 20),
		new /datum/data/vending_product("gimp outfit", /obj/item/clothing/under/vampire/nosferatu, 15),
		new /datum/data/vending_product("female gimp outfit", /obj/item/clothing/under/vampire/nosferatu/female, 15),
		new /datum/data/vending_product("rugged attire", /obj/item/clothing/under/vampire/gangrel, 15),
		new /datum/data/vending_product("female rugged attire", /obj/item/clothing/under/vampire/gangrel/female, 15),
		new /datum/data/vending_product("yellow sleeveless shirt", /obj/item/clothing/under/vampire/larry, 15),
		new /datum/data/vending_product("white sleeveless shirt", /obj/item/clothing/under/vampire/bandit, 15),
		new /datum/data/vending_product("white turtleneck", /obj/item/clothing/under/vampire/turtleneck_white, 15),
		new /datum/data/vending_product("black turtleneck", /obj/item/clothing/under/vampire/turtleneck_black, 15),
		new /datum/data/vending_product("red turtleneck", /obj/item/clothing/under/vampire/turtleneck_red, 15),
		new /datum/data/vending_product("navy turtleneck", /obj/item/clothing/under/vampire/turtleneck_navy, 15),
		new /datum/data/vending_product("biker outfit", /obj/item/clothing/under/vampire/biker, 15),
		new /datum/data/vending_product("burlesque outfit", /obj/item/clothing/under/vampire/burlesque, 15),
		new /datum/data/vending_product("daisy dukes", /obj/item/clothing/under/vampire/burlesque/daisyd, 10),
		new /datum/data/vending_product("black shoes", /obj/item/clothing/shoes/vampire, 10),
		new /datum/data/vending_product("brown shoes", /obj/item/clothing/shoes/vampire/brown, 10),
		new /datum/data/vending_product("white shoes", /obj/item/clothing/shoes/vampire/white, 10),
		new /datum/data/vending_product("black boots", /obj/item/clothing/shoes/vampire/jackboots, 10),
		new /datum/data/vending_product("work boots", /obj/item/clothing/shoes/vampire/jackboots/work, 10),
		new /datum/data/vending_product("white sneakers", /obj/item/clothing/shoes/vampire/sneakers, 10),
		new /datum/data/vending_product("red sneakers", /obj/item/clothing/shoes/vampire/sneakers/red, 10),
		new /datum/data/vending_product("high heels", /obj/item/clothing/shoes/vampire/heels, 35),
		new /datum/data/vending_product("red high heels", /obj/item/clothing/shoes/vampire/heels/red, 35),
		new /datum/data/vending_product("scaly shoes", /obj/item/clothing/shoes/vampire/businessscaly, 35),
		new /datum/data/vending_product("black shoes", /obj/item/clothing/shoes/vampire/businessblack, 35),
		new /datum/data/vending_product("black fur boots", /obj/item/clothing/shoes/vampire/blackfur, 35),
		new /datum/data/vending_product("brown fur boots", /obj/item/clothing/shoes/vampire/brownfur, 35),
		new /datum/data/vending_product("knee-high sneakers", /obj/item/clothing/shoes/vampire/pumped, 35),
		new /datum/data/vending_product("metal tip shoes", /obj/item/clothing/shoes/vampire/businesstip, 50),
		new /datum/data/vending_product("purple fur coat", /obj/item/clothing/suit/vampire/slickbackcoat, 500),
		new /datum/data/vending_product("too much fancy jacket", /obj/item/clothing/suit/vampire/majima_jacket, 100),
		new /datum/data/vending_product("labcoat", /obj/item/clothing/suit/vampire/labcoat, 75),
		new /datum/data/vending_product("fancy gray jacket", /obj/item/clothing/suit/vampire/fancy_gray, 50),
		new /datum/data/vending_product("fancy red jacket", /obj/item/clothing/suit/vampire/fancy_red, 50),
		new /datum/data/vending_product("black trenchcoat", /obj/item/clothing/suit/vampire/trench, 45),
		new /datum/data/vending_product("brown trenchcoat", /obj/item/clothing/suit/vampire/trench/alt, 35),
		new /datum/data/vending_product("leopard coat", /obj/item/clothing/suit/vampire/coat/leopard, 35),
		new /datum/data/vending_product("hoodie", /obj/item/clothing/suit/hooded/hoodie, 35),
		new /datum/data/vending_product("intruder pim hoodie", /obj/item/clothing/suit/hooded/hoodie/hoodie_pim, 35),
		new /datum/data/vending_product("brown coat", /obj/item/clothing/suit/vampire/coat, 15),
		new /datum/data/vending_product("green coat", /obj/item/clothing/suit/vampire/coat/alt, 15),
		new /datum/data/vending_product("black leather jacket", /obj/item/clothing/suit/vampire/jacket, 15),
		new /datum/data/vending_product("black coat", /obj/item/clothing/suit/vampire/coat/winter, 15),
		new /datum/data/vending_product("red coat", /obj/item/clothing/suit/vampire/coat/winter/alt, 15),
		new /datum/data/vending_product("yellow aviators", /obj/item/clothing/glasses/vampire/yellow, 20),
		new /datum/data/vending_product("red aviators", /obj/item/clothing/glasses/vampire/red, 20),
		new /datum/data/vending_product("sunglasses", /obj/item/clothing/glasses/vampire/sun, 20),
		new /datum/data/vending_product("prescription glasses", /obj/item/clothing/glasses/vampire/perception, 20),
		new /datum/data/vending_product("leather gloves", /obj/item/clothing/gloves/vampire/leather, 25),
		new /datum/data/vending_product("rubber gloves", /obj/item/clothing/gloves/vampire/cleaning, 15),
		new /datum/data/vending_product("latex gloves", /obj/item/clothing/gloves/vampire/latex, 5),
		new /datum/data/vending_product("black work gloves", /obj/item/clothing/gloves/vampire/work, 45),
		new /datum/data/vending_product("bandana", /obj/item/clothing/head/vampire/bandana, 10),
		new /datum/data/vending_product("red bandana", /obj/item/clothing/head/vampire/bandana/red, 10),
		new /datum/data/vending_product("black bandana", /obj/item/clothing/head/vampire/bandana/black, 10),
		new /datum/data/vending_product("baseball cap", /obj/item/clothing/head/vampire/baseballcap, 10),
		new /datum/data/vending_product("ushanka", /obj/item/clothing/head/vampire/ushanka, 20),
		new /datum/data/vending_product("beanie", /obj/item/clothing/head/vampire/beanie, 10),
		new /datum/data/vending_product("black beanie", /obj/item/clothing/head/vampire/beanie/black, 10),
		new /datum/data/vending_product("rough beanie", /obj/item/clothing/head/vampire/beanie/homeless, 10),
		new /datum/data/vending_product("red beret", /obj/item/clothing/head/beret, 10),
		new /datum/data/vending_product("black beret", /obj/item/clothing/head/beret/black, 10),
		new /datum/data/vending_product("white beret", /obj/item/clothing/head/beret/colorable, 10),
		new /datum/data/vending_product("scarf", /obj/item/clothing/neck/vampire/scarf, 10),
		new /datum/data/vending_product("blue tie", /obj/item/clothing/neck/tie/blue, 10),
		new /datum/data/vending_product("red tie", /obj/item/clothing/neck/tie/red, 10),
		new /datum/data/vending_product("black tie", /obj/item/clothing/neck/tie/black, 10),
		new /datum/data/vending_product("red scarf", /obj/item/clothing/neck/vampire/scarf/red, 10),
		new /datum/data/vending_product("blue scarf", /obj/item/clothing/neck/vampire/scarf/blue, 10),
		new /datum/data/vending_product("green scarf", /obj/item/clothing/neck/vampire/scarf/green, 10),
		new /datum/data/vending_product("white scarf", /obj/item/clothing/neck/vampire/scarf/white, 10),
		new /datum/data/vending_product("cross", /obj/item/card/id/hunter, 25),
		new /datum/data/vending_product("kasaya", /obj/item/clothing/suit/vampire/kasaya, 15),
		new /datum/data/vending_product("imam's robe", /obj/item/clothing/suit/vampire/imam, 15),
		new /datum/data/vending_product("orthodox robe", /obj/item/clothing/suit/vampire/orthodox, 15),
		new /datum/data/vending_product("hijab", /obj/item/clothing/head/vampire/hijab, 10),
		new /datum/data/vending_product("taqiyah", /obj/item/clothing/head/vampire/taqiyah, 10),
		new /datum/data/vending_product("kalimavkion", /obj/item/clothing/head/vampire/kalimavkion, 10),
		new /datum/data/vending_product("Nun Frock", /obj/item/clothing/suit/vampire/nun, 15),
		new /datum/data/vending_product("Wimple", /obj/item/clothing/head/vampire/nun, 10),
		new /datum/data/vending_product("duffelbag", /obj/item/storage/backpack/duffelbag, 100),
		new /datum/data/vending_product("backpack", /obj/item/storage/backpack, 100),
		new /datum/data/vending_product("satchel", /obj/item/storage/backpack/satchel, 100),
		new /datum/data/vending_product("leather satchel", /obj/item/storage/backpack/satchel/leather, 150),
		new /datum/data/vending_product("dress cane", /obj/item/cane, 50),
		new /datum/data/vending_product("white cane", /obj/item/cane/white, 30),
// requiem port
		new /datum/data/vending_product("prescription aviators", /obj/item/clothing/glasses/vampire/metalframe, 20),
		new /datum/data/vending_product("green glasses", /obj/item/clothing/glasses/vampire/green, 20),
		new /datum/data/vending_product("hipster glasses", /obj/item/clothing/glasses/vampire/retro, 20),
		new /datum/data/vending_product("safety goggles", /obj/item/clothing/glasses/vampire/safetygoggles, 20),
		new /datum/data/vending_product("big sunglasses", /obj/item/clothing/glasses/vampire/bigsunglasses, 20),
		new /datum/data/vending_product("thin sunglasses", /obj/item/clothing/glasses/vampire/thinsunglasses, 20),
		new /datum/data/vending_product("aviators", /obj/item/clothing/glasses/vampire/aviator, 20),
		new /datum/data/vending_product("green aviators", /obj/item/clothing/glasses/vampire/aviator_green, 20),
		new /datum/data/vending_product("blue aviators", /obj/item/clothing/glasses/vampire/aviator_blue, 20),
		new /datum/data/vending_product("red aviators", /obj/item/clothing/glasses/vampire/aviator_red, 20),
		new /datum/data/vending_product("black flats", /obj/item/clothing/shoes/vampire/flats, 35),
		new /datum/data/vending_product("brown flats", /obj/item/clothing/shoes/vampire/flats/brown, 35),
		new /datum/data/vending_product("white flats", /obj/item/clothing/shoes/vampire/flats/white, 35),
		new /datum/data/vending_product("red flats", /obj/item/clothing/shoes/vampire/flats/red, 35),
		new /datum/data/vending_product("orange flats", /obj/item/clothing/shoes/vampire/flats/orange, 35),
		new /datum/data/vending_product("purple flats", /obj/item/clothing/shoes/vampire/flats/purple, 35),
		new /datum/data/vending_product("blue flats", /obj/item/clothing/shoes/vampire/flats/blue, 35),
		new /datum/data/vending_product("blue sneakers", /obj/item/clothing/shoes/vampire/sneakers_blue, 15),
		new /datum/data/vending_product("dark red cap", /obj/item/clothing/head/vampire/redsoft, 30),
		new /datum/data/vending_product("grey flatcap", /obj/item/clothing/head/vampire/gent_cap, 30),
		new /datum/data/vending_product("black flatcap", /obj/item/clothing/head/vampire/flatcap, 30),
		new /datum/data/vending_product("white flatcap", /obj/item/clothing/head/vampire/flatcap/white, 30),
		new /datum/data/vending_product("green utility cap", /obj/item/clothing/head/vampire/greenutil, 30),
		new /datum/data/vending_product("tan utility cap", /obj/item/clothing/head/vampire/tanutil, 30),
		new /datum/data/vending_product("boater hat", /obj/item/clothing/head/vampire/boater_hat, 30),
		new /datum/data/vending_product("wool hat", /obj/item/clothing/head/vampire/woolhat, 30),
		new /datum/data/vending_product("blue wool hat", /obj/item/clothing/head/vampire/woolhat/woolhat_blue, 30),
		new /datum/data/vending_product("picture hat", /obj/item/clothing/head/vampire/picture_hat, 30),
		new /datum/data/vending_product("red picture hat", /obj/item/clothing/head/vampire/picture_hat/picture_red, 30),
		new /datum/data/vending_product("blue clipped tie", /obj/item/clothing/neck/vampire/tie/blueclip, 15),
		new /datum/data/vending_product("long blue tie", /obj/item/clothing/neck/vampire/tie/bluelong, 15),
		new /datum/data/vending_product("red clipped tie", /obj/item/clothing/neck/vampire/tie/redclip, 15),
		new /datum/data/vending_product("long red tie", /obj/item/clothing/neck/vampire/tie/redlong, 15),
		new /datum/data/vending_product("navy tie", /obj/item/clothing/neck/vampire/tie/navy, 15),
		new /datum/data/vending_product("yellow tie", /obj/item/clothing/neck/vampire/tie/yellow, 15),
		new /datum/data/vending_product("white tie", /obj/item/clothing/neck/vampire/tie/white, 15),
		new /datum/data/vending_product("green tie", /obj/item/clothing/neck/vampire/tie/darkgreen, 15),
		new /datum/data/vending_product("choker", /obj/item/clothing/neck/vampire/choker, 30),
		new /datum/data/vending_product("silver choker", /obj/item/clothing/neck/vampire/choker/silver, 30),
		new /datum/data/vending_product("ring choker", /obj/item/clothing/neck/vampire/choker/collar, 30),
		new /datum/data/vending_product("steel choker", /obj/item/clothing/neck/vampire/choker/collar/steel, 30),
		new /datum/data/vending_product("gold ring choker", /obj/item/clothing/neck/vampire/choker/collar/leatherg, 30),
		new /datum/data/vending_product("blue suit jacket", /obj/item/clothing/suit/vampire/toggle/suitjacket/blue, 45),
		new /datum/data/vending_product("purple suit jacket", /obj/item/clothing/suit/vampire/toggle/suitjacket/purple, 45),
		new /datum/data/vending_product("black suit jacket", /obj/item/clothing/suit/vampire/toggle/suitjacket/black, 45),
		new /datum/data/vending_product("black leather jacket", /obj/item/clothing/suit/vampire/toggle/leather, 45),
		new /datum/data/vending_product("brown leather jacket", /obj/item/clothing/suit/vampire/toggle/leather/brown, 45),
		new /datum/data/vending_product("black leather vest", /obj/item/clothing/suit/vampire/toggle/leather/sleeveless, 45),
		new /datum/data/vending_product("brown leather vest", /obj/item/clothing/suit/vampire/toggle/leather/brown_sleeveless, 45),
		new /datum/data/vending_product("grey zipper hoodie", /obj/item/clothing/suit/hooded/hoodie/grey, 45),
		new /datum/data/vending_product("black zipper hoodie", /obj/item/clothing/suit/hooded/hoodie/black, 45),
		new /datum/data/vending_product("red zipper hoodie", /obj/item/clothing/suit/hooded/hoodie/red, 45),
		new /datum/data/vending_product("blue zipper hoodie", /obj/item/clothing/suit/hooded/hoodie/blue, 45),
		new /datum/data/vending_product("orange zipper hoodie", /obj/item/clothing/suit/hooded/hoodie/orange, 45),
		new /datum/data/vending_product("pink zipper hoodie", /obj/item/clothing/suit/hooded/hoodie/pink, 45),
		new /datum/data/vending_product("yellow fur-lined jacket", /obj/item/clothing/suit/vampire/toggle/dep_jacket/yellow, 45),
		new /datum/data/vending_product("red fur-lined jacket", /obj/item/clothing/suit/vampire/toggle/dep_jacket/red, 45),
		new /datum/data/vending_product("white fur-lined jacket", /obj/item/clothing/suit/vampire/toggle/dep_jacket/white, 45),
		new /datum/data/vending_product("brown fur-lined jacket", /obj/item/clothing/suit/vampire/toggle/dep_jacket/brown, 45),
		new /datum/data/vending_product("grey fur-linked jacket", /obj/item/clothing/suit/vampire/toggle/dep_jacket, 45),
		new /datum/data/vending_product("blue fur-lined jacket", /obj/item/clothing/suit/vampire/toggle/dep_jacket/blue, 45),
		new /datum/data/vending_product("bomber jacket", /obj/item/clothing/suit/vampire/toggle/bomber, 45),
		new /datum/data/vending_product("asymmetrical bomber jacket", /obj/item/clothing/suit/vampire/toggle/bomber/retro_bomber, 45),
		new /datum/data/vending_product("grey flannel shirt", /obj/item/clothing/suit/vampire/flannel, 45),
		new /datum/data/vending_product("red flannel shirt", /obj/item/clothing/suit/vampire/flannel/red, 45),
		new /datum/data/vending_product("aqua flannel shirt", /obj/item/clothing/suit/vampire/flannel/aqua, 45),
		new /datum/data/vending_product("brown flannel shirt", /obj/item/clothing/suit/vampire/flannel/brown, 45),
		new /datum/data/vending_product("yellow parka", /obj/item/clothing/suit/hooded/hoodie/parka, 45),
		new /datum/data/vending_product("red parka", /obj/item/clothing/suit/hooded/hoodie/parka/red, 45),
		new /datum/data/vending_product("purple parka", /obj/item/clothing/suit/hooded/hoodie/parka/purple, 45),
		new /datum/data/vending_product("green parka", /obj/item/clothing/suit/hooded/hoodie/parka/green, 45),
		new /datum/data/vending_product("blue parka", /obj/item/clothing/suit/hooded/hoodie/parka/blue, 45),
		new /datum/data/vending_product("vintage parka", /obj/item/clothing/suit/hooded/hoodie/parka/vintage, 45),
		new /datum/data/vending_product("high-waisted trousers", /obj/item/clothing/under/vampire/hightrousers, 50),
		new /datum/data/vending_product("high-waisted skirt", /obj/item/clothing/under/vampire/highskirt, 50),
		new /datum/data/vending_product("ripped punk jeans", /obj/item/clothing/under/vampire/rippedpunk, 50),
		new /datum/data/vending_product("grey suit slacks", /obj/item/clothing/under/vampire/suitslacks, 35),
		new /datum/data/vending_product("white shirt and waistcoat", /obj/item/clothing/under/vampire/suit/waistcoat, 35),
		new /datum/data/vending_product("tan dress shirt", /obj/item/clothing/under/vampire/suit/tanshirt, 35),
		new /datum/data/vending_product("tan shirt and waistcoat", /obj/item/clothing/under/vampire/suit/tanshirtwaistcoat, 35),
		new /datum/data/vending_product("grey suit skirt", /obj/item/clothing/under/vampire/suit/greyskirt, 35),
		new /datum/data/vending_product("black suit slacks",/obj/item/clothing/under/vampire/suit/black, 35),
		new /datum/data/vending_product("black suit skirt", /obj/item/clothing/under/vampire/suit/blackskirt, 50),
		new /datum/data/vending_product("purple suit slacks", /obj/item/clothing/under/vampire/suit/purple, 35),
		new /datum/data/vending_product("charcoal suit slacks", /obj/item/clothing/under/vampire/suit/charcoal, 35),
		new /datum/data/vending_product("navy suit slacks", /obj/item/clothing/under/vampire/suit/navy, 35),
		new /datum/data/vending_product("burgundy suit slacks", /obj/item/clothing/under/vampire/suit/burgundy, 35),
		new /datum/data/vending_product("blue suit slacks", /obj/item/clothing/under/vampire/suit/blue, 35),
		new /datum/data/vending_product("checkered suit slacks", /obj/item/clothing/under/vampire/suit/checkered, 35),
		new /datum/data/vending_product("tan suit slacks", /obj/item/clothing/under/vampire/suit/tan, 35),
		new /datum/data/vending_product("purple suit skirt", /obj/item/clothing/under/vampire/suit/purpleskirt, 35),
		new /datum/data/vending_product("charcoal suit skirt", /obj/item/clothing/under/vampire/suit/charcoalskirt, 35),
		new /datum/data/vending_product("navy suit skirt", /obj/item/clothing/under/vampire/suit/navyskirt, 35),
		new /datum/data/vending_product("burgundy suit skirt", /obj/item/clothing/under/vampire/suit/burgundyskirt, 35),
		new /datum/data/vending_product("blue suit skirt", /obj/item/clothing/under/vampire/suit/blueskirt, 35),
		new /datum/data/vending_product("checkered suit skirt", /obj/item/clothing/under/vampire/suit/checkeredskirt, 35),
		new /datum/data/vending_product("tan suit skirt", /obj/item/clothing/under/vampire/suit/tanskirt, 35),
		new /datum/data/vending_product("black pantsuit", /obj/item/clothing/under/vampire/suit/blackfem, 100),
		new /datum/data/vending_product("corset and skirt outfit", /obj/item/clothing/under/vampire/dress/black_corset, 75),
		new /datum/data/vending_product("fancy red dress", /obj/item/clothing/under/vampire/dress/darkred, 75),
		new /datum/data/vending_product("red skirt", /obj/item/clothing/under/vampire/skirt/outfit, 35),
		new /datum/data/vending_product("blue plaid skirt", /obj/item/clothing/under/vampire/skirt/outfit/plaid_blue, 35),
		new /datum/data/vending_product("red plaid skirt", /obj/item/clothing/under/vampire/skirt/outfit/plaid_red, 35),
		new /datum/data/vending_product("purple plaid skirt", /obj/item/clothing/under/vampire/skirt/outfit/plaid_purple, 35),
		new /datum/data/vending_product("pentagram dress", /obj/item/clothing/under/vampire/dress/pentagram, 35),
		new /datum/data/vending_product("little black dress", /obj/item/clothing/under/vampire/dress/littleblackdress, 35),
		new /datum/data/vending_product("yellow swoop dress", /obj/item/clothing/under/vampire/dress/yellowswoop, 90),
		new /datum/data/vending_product("black tango dress", /obj/item/clothing/under/vampire/dress/blacktango, 35),
		new /datum/data/vending_product("slim qipao", /obj/item/clothing/under/vampire/dress/qipao2, 150),
		new /datum/data/vending_product("striped dress", /obj/item/clothing/under/vampire/dress/stripeddress, 35),
		new /datum/data/vending_product("sailor dress", /obj/item/clothing/under/vampire/dress/sailordress, 35),
		new /datum/data/vending_product("frilly black dress", /obj/item/clothing/under/vampire/dress/blackfrilly, 75),
		new /datum/data/vending_product("white lace dress", /obj/item/clothing/under/vampire/dress/wedding_gothic, 150),
		new /datum/data/vending_product("witchy dress", /obj/item/clothing/under/vampire/dress/old_wench_dress, 100),
		new /datum/data/vending_product("countess dress", /obj/item/clothing/under/vampire/dress/countess, 150),
		new /datum/data/vending_product("silk goddess dress", /obj/item/clothing/under/vampire/dress/goddess, 150),
		new /datum/data/vending_product("monochrome lace dress", /obj/item/clothing/under/vampire/dress/white_dress, 150),
		new /datum/data/vending_product("gold embroidered black dress", /obj/item/clothing/under/vampire/dress/sermon, 150),
		new /datum/data/vending_product("chain dress", /obj/item/clothing/under/vampire/dress/chain, 150),
		new /datum/data/vending_product("modest dress", /obj/item/clothing/under/vampire/dress/modest, 75),
		new /datum/data/vending_product("skater cargo pants", /obj/item/clothing/under/vampire/skater_boy, 75),
		new /datum/data/vending_product("skater skirt", /obj/item/clothing/under/vampire/skater_skirt, 75),
		new /datum/data/vending_product("strawberry lolita dress", /obj/item/clothing/under/vampire/dress/strawberrylolita, 150),
		new /datum/data/vending_product("widows dress", /obj/item/clothing/under/vampire/dress/matron, 150),
		new /datum/data/vending_product("little gothic dress", /obj/item/clothing/under/vampire/dress/maiden, 150),
		new /datum/data/vending_product("open front silk shirt", /obj/item/clothing/under/vampire/novella, 150),
		new /datum/data/vending_product("sheer black lace dress", /obj/item/clothing/under/vampire/dress/laceblack, 150),
		new /datum/data/vending_product("royal red suit", /obj/item/clothing/under/vampire/royalredsuit, 150),
		new /datum/data/vending_product("dark band t-shirt", /obj/item/clothing/under/vampire/bandshirt_dark, 35),
		new /datum/data/vending_product("light band t-shirt", /obj/item/clothing/under/vampire/bandshirt_light, 35),
		new /datum/data/vending_product("grey suspenders and trousers", /obj/item/clothing/under/vampire/suspenders, 35),
		new /datum/data/vending_product("black suspenders and trousers", /obj/item/clothing/under/vampire/suspenders_fancy, 35),
		new /datum/data/vending_product("red button-up", /obj/item/clothing/under/vampire/buttonup_red, 35),
		new /datum/data/vending_product("black baggy pants", /obj/item/clothing/under/vampire/pants/baggy, 35),
		new /datum/data/vending_product("black jeans", /obj/item/clothing/under/vampire/pants/blackjeans, 35),
		new /datum/data/vending_product("baggy black jeans", /obj/item/clothing/under/vampire/pants/blackjeansbaggy, 35),
		new /datum/data/vending_product("ripped black jeans", /obj/item/clothing/under/vampire/pants/blackjeansripped, 35),
		new /datum/data/vending_product("grey jeans", /obj/item/clothing/under/vampire/pants/greyjeans, 35),
		new /datum/data/vending_product("baggy grey jeans", /obj/item/clothing/under/vampire/pants/greyjeansbaggy, 35),
		new /datum/data/vending_product("ripped grey jeans", /obj/item/clothing/under/vampire/pants/greyjeansripped, 35),
		new /datum/data/vending_product("baggy classic jeans", /obj/item/clothing/under/vampire/pants/bluejeansbaggy, 35),
		new /datum/data/vending_product("ripped blue jeans", /obj/item/clothing/under/vampire/pants/bluejeansripped, 35),
		new /datum/data/vending_product("stonewashed jeans", /obj/item/clothing/under/vampire/pants/mustangjeans, 35),
		new /datum/data/vending_product("baggy stonewashed jeans", /obj/item/clothing/under/vampire/pants/mustangjeansbaggy, 35),
		new /datum/data/vending_product("ripped stonewashed jeans", /obj/item/clothing/under/vampire/pants/mustangjeansripped, 35),
		new /datum/data/vending_product("baggy camo pants", /obj/item/clothing/under/vampire/pants/camobaggy, 35),
		new /datum/data/vending_product("white pants", /obj/item/clothing/under/vampire/pants/white, 35),
		new /datum/data/vending_product("baggy white pants", /obj/item/clothing/under/vampire/pants/whitebaggy, 35),
		new /datum/data/vending_product("red pants", /obj/item/clothing/under/vampire/pants/red, 35),
		new /datum/data/vending_product("baggy red pants", /obj/item/clothing/under/vampire/pants/redbaggy, 35),
		new /datum/data/vending_product("khaki pants", /obj/item/clothing/under/vampire/pants/khaki, 35),
		new /datum/data/vending_product("baggy khaki pants", /obj/item/clothing/under/vampire/pants/khakibaggy, 35),
		new /datum/data/vending_product("black jeans shorts", /obj/item/clothing/under/vampire/shorts, 35),
		new /datum/data/vending_product("black jean shorts shorts", /obj/item/clothing/under/vampire/shorts/blackshortshort, 35),
		new /datum/data/vending_product("blue jean shorts", /obj/item/clothing/under/vampire/shorts/jeanshorts, 35),
		new /datum/data/vending_product("blue jean short shorts", /obj/item/clothing/under/vampire/shorts/jeanshortshort, 35),
		new /datum/data/vending_product("stonewashed jean shorts", /obj/item/clothing/under/vampire/shorts/mustangjeanshorts, 35),
		new /datum/data/vending_product("stonewashed jean short shorts", /obj/item/clothing/under/vampire/shorts/mustangjeanshortshort, 35),
		new /datum/data/vending_product("khaki shorts", /obj/item/clothing/under/vampire/shorts/khaki, 35),
		new /datum/data/vending_product("black leather skirt", /obj/item/clothing/under/vampire/shorts/skirt, 35),
		new /datum/data/vending_product("short denim skirt", /obj/item/clothing/under/vampire/shorts/skirtdenim, 35),
		new /datum/data/vending_product("white widows dress", /obj/item/clothing/under/vampire/dress/matron_white, 150),
		new /datum/data/vending_product("pinup skirt", /obj/item/clothing/under/vampire/pinup, 150),
		new /datum/data/vending_product("white shawl", /obj/item/clothing/suit/vampire/shawl_white, 50),
		new /datum/data/vending_product("charcoal suit jacket", /obj/item/clothing/suit/vampire/jacket/charcoalsuit, 80),
		new /datum/data/vending_product("navy suit jacket", /obj/item/clothing/suit/vampire/jacket/navysuit, 80),
		new /datum/data/vending_product("burgundy suit jacket", /obj/item/clothing/suit/vampire/jacket/burgundysuit, 80),
		new /datum/data/vending_product("checkered suit jacket", /obj/item/clothing/suit/vampire/jacket/checkeredsuit, 80),
		new /datum/data/vending_product("tan suit jacket", /obj/item/clothing/suit/vampire/jacket/tansuit, 80),
	)
