/obj/structure/retail/costume_store
	desc = "Purchase a mask for that ugly mug."
	products_list = list(
		new /datum/data/vending_product("balaclava",	 /obj/item/clothing/mask/vampire/balaclava,	10),
		new /datum/data/vending_product("bear mask",	 /obj/item/clothing/mask/animal/rat/bear,	13),
		new /datum/data/vending_product("rat mask",	/obj/item/clothing/mask/animal/rat,	10),
		new /datum/data/vending_product("bee mask",	/obj/item/clothing/mask/animal/rat/bee,	12),
		new /datum/data/vending_product("fox mask",	/obj/item/clothing/mask/animal/rat/fox,	10),
		new /datum/data/vending_product("bat mask",	/obj/item/clothing/mask/animal/rat/bat,	15),
		new /datum/data/vending_product("raven mask",	/obj/item/clothing/mask/animal/rat/raven,	20),
		new /datum/data/vending_product("jackal mask",	 /obj/item/clothing/mask/animal/rat/jackal,	20),
		new /datum/data/vending_product("medical mask",	/obj/item/clothing/mask/surgical,	10),
		new /datum/data/vending_product("mummy mask",	/obj/item/clothing/mask/mummy,	15),
		new /datum/data/vending_product("scarecrow mask",	/obj/item/clothing/mask/scarecrow,	10),
		new /datum/data/vending_product("respirator",	/obj/item/clothing/mask/vampire,	35),
		new /datum/data/vending_product("black and gold luchador mask",	/obj/item/clothing/mask/luchador,	10),
		new /datum/data/vending_product("green luchador mask",	/obj/item/clothing/mask/luchador/tecnicos,	10),
		new /datum/data/vending_product("red and blue luchador mask",	/obj/item/clothing/mask/luchador/rudos,	10),
		new /datum/data/vending_product("Venetian mask",	/obj/item/clothing/mask/vampire/venetian_mask,	30),
		new /datum/data/vending_product("fancy Venetian mask",	/obj/item/clothing/mask/vampire/venetian_mask/fancy,	200),
		new /datum/data/vending_product("jester mask",	/obj/item/clothing/mask/vampire/venetian_mask/jester,	50),
		new /datum/data/vending_product("bloody mask",	/obj/item/clothing/mask/vampire/venetian_mask/scary,	30),
		new /datum/data/vending_product("comedy mask", /obj/item/clothing/mask/vampire/comedy,	25),
		new /datum/data/vending_product("tragedy mask", /obj/item/clothing/mask/vampire/tragedy,	25),
		new /datum/data/vending_product("shemagh",	 /obj/item/clothing/mask/vampire/shemagh,	20),
		new /datum/data/vending_product("eyepatch", /obj/item/clothing/glasses/apoc/eyepatch, 5),
		new /datum/data/vending_product("magic eye seal", /obj/item/clothing/glasses/apoc/eyepatch/medical, 5),
		new /datum/data/vending_product("rose eyepatch", /obj/item/clothing/glasses/apoc/eyepatch/rose, 5),
		new /datum/data/vending_product("blindfold", /obj/item/clothing/glasses/apoc/blindfold, 5),
		new /datum/data/vending_product("trick blindfold", /obj/item/clothing/glasses/apoc/blindfold/trick, 5),
		new /datum/data/vending_product("white robes",	/obj/item/clothing/suit/hooded/robes,	40),
		new /datum/data/vending_product("black robes",	/obj/item/clothing/suit/hooded/robes/black,	40),
		new /datum/data/vending_product("grey robes",	/obj/item/clothing/suit/hooded/robes/grey,	40),
		new /datum/data/vending_product("dark red robes",	/obj/item/clothing/suit/hooded/robes/darkred,	40),
		new /datum/data/vending_product("yellow robes",	/obj/item/clothing/suit/hooded/robes/yellow,	40),
		new /datum/data/vending_product("green robes",	/obj/item/clothing/suit/hooded/robes/green,	40),
		new /datum/data/vending_product("red robes",	/obj/item/clothing/suit/hooded/robes/red,	40),
		new /datum/data/vending_product("blue robes", /obj/item/clothing/suit/hooded/robes/blue,	40),
		new /datum/data/vending_product("purple robes",	/obj/item/clothing/suit/hooded/robes/purple,	40),
		new /datum/data/vending_product("blue wizard hat",	/obj/item/clothing/head/vampire/wizard/blue, 25),
		new /datum/data/vending_product("red wizard hat",	/obj/item/clothing/head/vampire/wizard/red, 25),
		new /datum/data/vending_product("yellow wizard hat",	/obj/item/clothing/head/vampire/wizard/yellow, 25),
		new /datum/data/vending_product("green wizard hat",	/obj/item/clothing/head/vampire/wizard/green, 25),
		new /datum/data/vending_product("dark red wizard hat",	/obj/item/clothing/head/vampire/wizard/darkred, 25),
		new /datum/data/vending_product("grey wizard hat",	/obj/item/clothing/head/vampire/wizard/grey, 25),
		new /datum/data/vending_product("white wizard hat",	/obj/item/clothing/head/vampire/wizard/white, 25),
		new /datum/data/vending_product("black wizard hat",	/obj/item/clothing/head/vampire/wizard/black, 25),
		new /datum/data/vending_product("purple wizard hat",	/obj/item/clothing/head/vampire/wizard/purple, 25)
	)
