/obj/structure/retail/gas_station
	products_list = list(new /datum/data/vending_product("full gas can",	/obj/item/gas_can/full,	250),
		new /datum/data/vending_product("tire iron",		/obj/item/melee/vampirearms/tire,	50),
		new /datum/data/vending_product("Spray Paint",		/obj/item/toy/crayon/spraycan,		25),
		new /datum/data/vending_product("Hair Spray",		/obj/item/dyespray,		10),
		new /datum/data/vending_product("malboro",	/obj/item/storage/fancy/cigarettes/cigpack_robust,	50),
		new /datum/data/vending_product("newport",		/obj/item/storage/fancy/cigarettes/cigpack_xeno,	30),
		new /datum/data/vending_product("camel",	/obj/item/storage/fancy/cigarettes/dromedaryco,	30),
		new /datum/data/vending_product("zippo lighter",	/obj/item/lighter,	20),
		new /datum/data/vending_product("lighter",		/obj/item/lighter/greyscale,	10),
		new /datum/data/vending_product("chocolate bar",	/obj/item/food/vampire/bar),
		new /datum/data/vending_product("chips",	/obj/item/food/vampire/crisps),
		new /datum/data/vending_product("water bottle",	/obj/item/reagent_containers/food/drinks/bottle/vampirewater),
		new /datum/data/vending_product("soda can",	/obj/item/reagent_containers/food/drinks/soda_cans/vampiresoda),
		new /datum/data/vending_product("two liter cola bottle",	/obj/item/reagent_containers/food/drinks/bottle/vampirecola),
		new /datum/data/vending_product("cola can",	/obj/item/reagent_containers/food/drinks/soda_cans/vampirecola),
		new /datum/data/vending_product("summer thaw", /obj/item/reagent_containers/food/drinks/bottle/vampirecola/summer_thaw),
		new /datum/data/vending_product("milk",	/obj/item/reagent_containers/food/condiment/vampiremilk,	5),
		new /datum/data/vending_product("beer bottle",	/obj/item/reagent_containers/food/drinks/beer/vampire,	10),
		new /datum/data/vending_product("blue stripe", /obj/item/reagent_containers/food/drinks/beer/vampire/blue_stripe, 8),
		new /datum/data/vending_product("candle pack",	/obj/item/storage/fancy/candle_box,	12),
		new /datum/data/vending_product("bruise pack", /obj/item/stack/medical/bruise_pack, 100),
		new /datum/data/vending_product("respirator",	/obj/item/clothing/mask/vampire,	35)
	)
