/obj/structure/retail/hot_ishu
	products_list = list(
		new /datum/data/vending_product("\"Vase\"",	/obj/item/bong,		50),
		new /datum/data/vending_product("cross",	/obj/item/card/id/hunter,  25),
		new /datum/data/vending_product("backpack",	/obj/item/storage/backpack,	100),
		new /datum/data/vending_product("black grunge outfit",	/obj/item/clothing/under/vampire/black,	20),
		new /datum/data/vending_product("burlesque outfit", /obj/item/clothing/under/vampire/burlesque,	15),
		new /datum/data/vending_product("female gimp outfit",	/obj/item/clothing/under/vampire/nosferatu/female,	15),
		new /datum/data/vending_product("female punk attire ",	/obj/item/clothing/under/vampire/brujah/female,	20),
		new /datum/data/vending_product("gimp outfit",	/obj/item/clothing/under/vampire/nosferatu,	15),
		new /datum/data/vending_product("gothic clothes",	/obj/item/clothing/under/vampire/gothic,	20),
		new /datum/data/vending_product("gothic attire",	/obj/item/clothing/under/vampire/brujah,	20),
		new /datum/data/vending_product("grimey pants",	/obj/item/clothing/under/vampire/malkavian,	20),
		new /datum/data/vending_product("hoodie", /obj/item/clothing/suit/hooded/hoodie, 15),
		new /datum/data/vending_product("intruder pim hoodie", /obj/item/clothing/suit/hooded/hoodie/hoodie_pim, 20),
		new /datum/data/vending_product("jacket",	/obj/item/clothing/suit/vampire/jacket,	15),
		new /datum/data/vending_product("odd Goth schoolgirl attire",	/obj/item/clothing/under/vampire/malkavian/female,	20),
		new /datum/data/vending_product("pentagram shirt",	/obj/item/clothing/under/vampire/baali,	20),
		new /datum/data/vending_product("pentagram skirt",	/obj/item/clothing/under/vampire/baali/female,	20),
		new /datum/data/vending_product("punk outfit",	/obj/item/clothing/under/vampire/emo,	20),
		new /datum/data/vending_product("red hipster outfit",	/obj/item/clothing/under/vampire/red,	20),
	)
