#define SEPT_NAME "Sept of the Western Eye"

#define TRIBE_NONE "Ronin"

#define TRIBE_GALESTALKERS "Galestalkers"
#define TRIBE_CHILDRENOFGAIA "Children of Gaia"
#define TRIBE_GHOSTCOUNCIL "Ghost Council"
#define TRIBE_HARTWARDENS "Hart Wardens"
#define TRIBE_GETOFFENRIS "Get of Fenris"
#define TRIBE_BLACKFURIES "Black Furies"
#define TRIBE_SILVERFANGS "Silver Fangs"
#define TRIBE_SILENTSTRIDERS "Silent Striders"
#define TRIBE_REDTALONS "Red Talons"
#define TRIBE_STARGAZERS "Stargazers"
#define TRIBE_GLASSWALKERS "Glass Walkers"
#define TRIBE_BONEGNAWERS "Bone Gnawers"
#define TRIBE_SHADOWLORDS "Shadow Lords"
#define TRIBE_BLACKSPIRALDANCERS "Black Spiral Dancers"
#define TRIBE_CORAX "Corax"

#define TRIBE_ALL list(TRIBE_NONE, TRIBE_GALESTALKERS, TRIBE_CHILDRENOFGAIA, TRIBE_GHOSTCOUNCIL, TRIBE_HARTWARDENS, TRIBE_GETOFFENRIS, TRIBE_BLACKFURIES, TRIBE_SILVERFANGS, TRIBE_SILENTSTRIDERS, TRIBE_REDTALONS, TRIBE_STARGAZERS, TRIBE_GLASSWALKERS, TRIBE_BONEGNAWERS, TRIBE_SHADOWLORDS, TRIBE_BLACKSPIRALDANCERS, TRIBE_CORAX)

#define TRIBE_GAIA list(TRIBE_GALESTALKERS, TRIBE_CHILDRENOFGAIA, TRIBE_GHOSTCOUNCIL, TRIBE_HARTWARDENS, TRIBE_GETOFFENRIS, TRIBE_BLACKFURIES, TRIBE_SILVERFANGS, TRIBE_SILENTSTRIDERS, TRIBE_REDTALONS, TRIBE_STARGAZERS, TRIBE_GLASSWALKERS, TRIBE_BONEGNAWERS, TRIBE_SHADOWLORDS, TRIBE_CORAX)

#define TRIBE_WYLD list(TRIBE_GALESTALKERS, TRIBE_CHILDRENOFGAIA, TRIBE_GHOSTCOUNCIL, TRIBE_HARTWARDENS, TRIBE_GETOFFENRIS, TRIBE_BLACKFURIES, TRIBE_SILVERFANGS, TRIBE_SILENTSTRIDERS, TRIBE_REDTALONS, TRIBE_STARGAZERS, TRIBE_SHADOWLORDS, TRIBE_CORAX)

#define TRIBE_WEAVER list(TRIBE_GLASSWALKERS, TRIBE_BONEGNAWERS)

#define TRIBE_WYRM list(TRIBE_BLACKSPIRALDANCERS)

