/proc/creed_to_virtue(creed)
	var/static/indexed_by_creed = list(
			CREED_BYSTANDER = VIRTUE_NONE,
			CREED_DEFENDER = VIRTUE_ZEAL,
			CREED_JUDGE = VIRTUE_ZEAL,
			CREED_AVENGER = VIRTUE_ZEAL,
			CREED_MARTYR = VIRTUE_MERCY,
			CREED_INNOCENT = VIRTUE_MERCY,
			CREED_REDEEMER = VIRTUE_MERCY,
			CREED_VISIONARY = VIRTUE_VISION,
			CREED_HERMIT = VIRTUE_VISION,
			CREED_WAYWARD = VIRTUE_VISION
		)
	return indexed_by_creed[creed]
